"""Models for ESI Link responses.

These models represent the data returned by ESI endpoints. The model is named after the
operation_id for the endpoint. Where the response model is a container,
items in the container will be named with the suffix "Item" to distinguish them from the
container itself.

Fields may also be added to the container that have data from the query parameters or
other metadata that is not directly from the ESI response, but is relevant to the calculations.

The data may be organized in collections in a different form than the raw ESI response
for ease of use in calculations. For example, market orders may be collected by type ID
and buy/sell status, rather than being a flat list of orders as returned by ESI.

This is a limited set of models defined for convenience in the Argus modules,
and is not intended to be a comprehensive set of models for all ESI responses. For a
more comprehensive information on the response data from the EVE Esi, see the schema docs.
"""

import logging
from abc import abstractmethod
from dataclasses import dataclass
from typing import Any, Literal, Self, TypedDict

from pydantic import BaseModel

from esi_link.models_and_protocols import ResponseData

logger = logging.getLogger(__name__)


class EsiDataModel(BaseModel):
    """Base class for ESI data models."""

    operation_id: str
    """The ESI operation ID that this model represents."""
    response_date: str
    """The date and time when the response was generated by the ESI server, as an RFC 2822 string."""
    received_at: int
    """The date and time when the data was received from ESI, as a Unix timestamp in nanoseconds."""

    @classmethod
    @abstractmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create an instance of the model from ESI response data."""
        raise NotImplementedError("Subclasses must implement from_response_data method")


# ------------------------------------------------------------------------------
# Character Models
# ------------------------------------------------------------------------------


@dataclass(slots=True)
class GetCharactersCharacterIdBlueprintsItem:
    item_id: int
    """Unique ID for this item."""
    location_flag: str
    """Type of the location_id."""
    location_id: int
    """References a station, a ship or an item_id if this blueprint
          is located within a container. If the return value is an item_id, then the
          Character AssetList API must be queried to find the container using the
          given item_id to determine the correct location of the Blueprint."""
    material_efficiency: int
    """Material Efficiency Level of the blueprint."""
    quantity: int
    """A range of numbers with a minimum of -2 and no maximum value
          where -1 is an original and -2 is a copy. It can be a positive integer if
          it is a stack of blueprint originals fresh from the market (e.g. no activities
          performed on them yet)."""
    runs: int
    """Number of runs remaining if the blueprint is a copy, -1 if it is an original."""
    time_efficiency: int
    """Time Efficiency Level of the blueprint."""
    type_id: int


class GetCharactersCharacterIdBlueprints(EsiDataModel):
    character_id: int
    blueprints: dict[int, list[GetCharactersCharacterIdBlueprintsItem]]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetCharactersCharacterIdBlueprints instance from ESI response data."""
        operation_id = "GetCharactersCharacterIdBlueprints"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        data_dict: dict[int, list[GetCharactersCharacterIdBlueprintsItem]] = {}
        for item in response_data.data:
            blueprint_item = GetCharactersCharacterIdBlueprintsItem(**item)
            if blueprint_item.type_id not in data_dict:
                data_dict[blueprint_item.type_id] = []
            data_dict[blueprint_item.type_id].append(blueprint_item)
        model_dict: dict[str, Any] = {
            "operation_id": operation_id,
            "response_date": response_data.response_date,
            "received_at": response_data.received_at,
            "character_id": int(response_data.request.path_parameters["character_id"]),
            "blueprints": data_dict,
        }
        return cls.model_validate(model_dict)


@dataclass(slots=True, kw_only=True)
class GetCharactersCharacterIdIndustryJobsItem:
    activity_id: int
    blueprint_id: int
    blueprint_location_id: int
    blueprint_type_id: int
    completed_character_id: int | None = None
    completed_date: str | None = None
    cost: float | None = None
    duration: int
    end_date: str
    facility_id: int
    installer_id: int
    job_id: int
    licensed_runs: int | None = None
    output_location_id: int
    pause_date: str | None = None
    probability: float | None = None
    product_type_id: int | None = None
    runs: int
    start_date: str
    station_id: int
    status: str
    successful_runs: int | None = None


class GetCharactersCharacterIdIndustryJobs(EsiDataModel):
    character_id: int
    jobs: list[GetCharactersCharacterIdIndustryJobsItem]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetCharactersCharacterIdIndustryJobs instance from ESI response data."""
        operation_id = "GetCharactersCharacterIdIndustryJobs"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        data_list: list[GetCharactersCharacterIdIndustryJobsItem] = []
        for item in response_data.data:
            job_item = GetCharactersCharacterIdIndustryJobsItem(**item)
            data_list.append(job_item)
        model_dict: dict[str, Any] = {
            "operation_id": operation_id,
            "response_date": response_data.response_date,
            "received_at": response_data.received_at,
            "character_id": int(response_data.request.path_parameters["character_id"]),
            "jobs": data_list,
        }
        return cls.model_validate(model_dict)


@dataclass(slots=True, kw_only=True)
class GetCharactersCharacterIdItem:
    alliance_id: int | None = None
    """The alliance that the character is a member of, if any."""
    birthday: str
    bloodline_id: int
    corporation_id: int
    description: str | None = None
    faction_id: int | None = None
    gender: str
    name: str
    race_id: int
    security_status: float | None = None
    title: str | None = None


class GetCharactersCharacterId(EsiDataModel):
    character_id: int
    character_info: GetCharactersCharacterIdItem

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetCharactersCharacterId instance from ESI response data."""
        operation_id = "GetCharactersCharacterId"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        try:
            character_info = GetCharactersCharacterIdItem(**response_data.data)
            data_dict = {"character_info": character_info}
        except Exception as e:
            raise ValueError(f"Error parsing character info: {e}") from e
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "character_id": int(
                    response_data.request.path_parameters["character_id"]
                ),
                **data_dict,
            }
        )


# ------------------------------------------------------------------------------
# Corporation Models
# ------------------------------------------------------------------------------


@dataclass(slots=True)
class GetCorporationsCorporationIdBlueprintsItem:
    item_id: int
    """Unique ID for this item."""
    location_flag: str
    """Type of the location_id."""
    location_id: int
    """References a station, a ship or an item_id if this blueprint
          is located within a container. If the return value is an item_id, then the
          Character AssetList API must be queried to find the container using the
          given item_id to determine the correct location of the Blueprint."""
    material_efficiency: int
    """Material Efficiency Level of the blueprint."""
    quantity: int
    """A range of numbers with a minimum of -2 and no maximum value
          where -1 is an original and -2 is a copy. It can be a positive integer if
          it is a stack of blueprint originals fresh from the market (e.g. no activities
          performed on them yet)."""
    runs: int
    """Number of runs remaining if the blueprint is a copy, -1 if it is an original."""
    time_efficiency: int
    """Time Efficiency Level of the blueprint."""
    type_id: int


class GetCorporationsCorporationIdBlueprints(EsiDataModel):
    corporation_id: int
    blueprints: dict[int, list[GetCorporationsCorporationIdBlueprintsItem]]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetCorporationsCorporationIdBlueprints instance from ESI response data."""
        operation_id = "GetCorporationsCorporationIdBlueprints"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        data_dict: dict[int, list[GetCorporationsCorporationIdBlueprintsItem]] = {}
        for item in response_data.data:
            blueprint_item = GetCorporationsCorporationIdBlueprintsItem(**item)
            if blueprint_item.type_id not in data_dict:
                data_dict[blueprint_item.type_id] = []
            data_dict[blueprint_item.type_id].append(blueprint_item)
        model_dict: dict[str, Any] = {
            "operation_id": operation_id,
            "response_date": response_data.response_date,
            "received_at": response_data.received_at,
            "corporation_id": int(
                response_data.request.path_parameters["corporation_id"]
            ),
            "blueprints": data_dict,
        }
        return cls.model_validate(model_dict)


@dataclass(slots=True, kw_only=True)
class GetCorporationsCorporationIdIndustryJobsItem:
    activity_id: int
    blueprint_id: int
    blueprint_location_id: int
    """The location of the blueprint, which may be a station, a ship or an item_id if 
    the blueprint is located within a container. If the value is an item_id, then the 
    Character AssetList API must be queried to find the container using the given 
    item_id to determine the correct location of the Blueprint."""
    blueprint_type_id: int
    completed_character_id: int | None = None
    completed_date: str | None = None
    cost: float | None = None
    duration: int
    end_date: str
    facility_id: int
    installer_id: int
    job_id: int
    licensed_runs: int | None = None
    location_id: int
    output_location_id: int
    """The location of the job, which may be a station, a ship or an item_id if the job 
    is located within a container."""
    pause_date: str | None = None
    probability: float | None = None
    product_type_id: int | None = None
    runs: int
    start_date: str
    status: str
    successful_runs: int | None = None


class GetCorporationsCorporationIdIndustryJobs(EsiDataModel):
    corporation_id: int
    jobs: list[GetCorporationsCorporationIdIndustryJobsItem]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetCorporationsCorporationIdIndustryJobs instance from ESI response data."""
        operation_id = "GetCorporationsCorporationIdIndustryJobs"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        data_list: list[GetCorporationsCorporationIdIndustryJobsItem] = []
        for item in response_data.data:
            job_item = GetCorporationsCorporationIdIndustryJobsItem(**item)
            data_list.append(job_item)
        model_dict: dict[str, Any] = {
            "operation_id": operation_id,
            "response_date": response_data.response_date,
            "received_at": response_data.received_at,
            "corporation_id": int(
                response_data.request.path_parameters["corporation_id"]
            ),
            "jobs": data_list,
        }
        return cls.model_validate(model_dict)


class GetUniverseTypes(EsiDataModel):
    type_ids: list[int]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetUniverseTypes instance from ESI response data."""
        operation_id = "GetUniverseTypes"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        type_ids = [int(item) for item in response_data.data]
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "type_ids": type_ids,
            }
        )


@dataclass(slots=True, kw_only=True)
class PostUniverseNamesItem:
    id_: int
    name: str
    category: str


class PostUniverseNames(EsiDataModel):
    names: dict[int, PostUniverseNamesItem]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a PostUniverseNames instance from ESI response data."""
        operation_id = "PostUniverseNames"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        names_dict: dict[int, PostUniverseNamesItem] = {}
        for item in response_data.data:
            name_item = PostUniverseNamesItem(
                id_=item["id"], name=item["name"], category=item["category"]
            )
            names_dict[name_item.id_] = name_item
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "names": names_dict,
            }
        )

    def name(self, id_: int) -> str:
        """Get the name for a given ID, or return a default string if the ID is not found."""
        if id_ not in self.names:
            logger.warning(f"ID {id_} not found in names dictionary.")
            return f"Unknown ID {id_}"
        return self.names[id_].name

    def category(self, id_: int) -> str:
        """Get the category for a given ID, or return a default string if the ID is not found."""
        if id_ not in self.names:
            logger.warning(f"ID {id_} not found in names dictionary.")
            return f"Unknown ID {id_}"
        return self.names[id_].category


# ------------------------------------------------------------------------------
# Industry Models
# ------------------------------------------------------------------------------


class CostIndexActivity(TypedDict):
    activity: Literal[
        "manufacturing",
        "researching_time_efficiency",
        "researching_material_efficiency",
        "copying",
        "invention",
        "reaction",
    ]
    cost_index: float


@dataclass(slots=True)
class GetIndustrySystemsItem:
    solar_system_id: int
    cost_indices: list[CostIndexActivity]

    @property
    def cost_index_by_activity(self) -> dict[str, float | str]:
        """Get a mapping of activity names to their corresponding cost indices."""
        for ci in self.cost_indices:
            print(ci)
        return {ci["activity"]: ci["cost_index"] for ci in self.cost_indices}


class GetIndustrySystems(EsiDataModel):
    systems: dict[int, GetIndustrySystemsItem]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetIndustrySystems instance from ESI response data."""
        operation_id = "GetIndustrySystems"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        data_dict: dict[int, GetIndustrySystemsItem] = {}
        for item in response_data.data:
            system_item = GetIndustrySystemsItem(**item)
            data_dict[system_item.solar_system_id] = system_item
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "systems": data_dict,
            }
        )


# ------------------------------------------------------------------------------
# Market Models
# ------------------------------------------------------------------------------


@dataclass(slots=True)
class GetMarketsPricesItem:
    type_id: int
    """The item type ID of the market price."""
    adjusted_price: float | None = None
    """The adjusted price of the item, calculated as a volume-weighted average of recent market prices."""
    average_price: float | None = None
    """The average price of the item, calculated as a simple average of recent market prices."""


class GetMarketsPrices(EsiDataModel):
    prices: dict[int, GetMarketsPricesItem]
    """A mapping of item type IDs to their corresponding market price information."""

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetMarketsPrices instance from ESI response data."""
        operation_id = "GetMarketsPrices"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        prices_dict: dict[int, GetMarketsPricesItem] = {}
        for item in response_data.data:
            price_item = GetMarketsPricesItem(**item)
            prices_dict[price_item.type_id] = price_item
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "prices": prices_dict,
            }
        )


@dataclass(slots=True)
class GetMarketsRegionIdHistoryItem:
    average: float
    date: str
    highest: float
    lowest: float
    order_count: int
    volume: float


class GetMarketsRegionIdHistory(EsiDataModel):
    region_id: int
    type_id: int
    history: dict[str, GetMarketsRegionIdHistoryItem]

    @property
    def most_recent_date(self) -> str | None:
        """Get the most recent date from the market history data."""
        return next(iter(self.history.keys())) if self.history else None

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetMarketsRegionIdHistory instance from ESI response data."""
        operation_id = "GetMarketsRegionIdHistory"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        region_id = int(response_data.request.path_parameters["region_id"])
        type_id = int(response_data.request.path_parameters["type_id"])
        history_dict: dict[str, GetMarketsRegionIdHistoryItem] = {}
        sorted_data = sorted(response_data.data, key=lambda x: x["date"], reverse=True)
        for item in sorted_data:
            history_item = GetMarketsRegionIdHistoryItem(**item)
            history_dict[history_item.date] = history_item
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "region_id": region_id,
                "type_id": type_id,
                "history": history_dict,
            }
        )


@dataclass(slots=True)
class GetMarketsRegionIdOrdersItem:
    """Represents a market order detail."""

    duration: int
    is_buy_order: bool
    issued: str
    location_id: int
    min_volume: int
    order_id: int
    price: float
    range: str
    system_id: int
    type_id: int
    volume_remain: int
    volume_total: int


@dataclass(slots=True)
class CollectedMarketOrders:
    """Represents collected market orders for a specific region and type."""

    region_id: int
    type_id: int
    buy_orders: list[GetMarketsRegionIdOrdersItem]
    sell_orders: list[GetMarketsRegionIdOrdersItem]


class GetMarketsRegionIdOrders(EsiDataModel):
    """Represents market orders for a specific region."""

    region_id: int
    orders: dict[int, CollectedMarketOrders]

    @classmethod
    def from_response_data(cls, response_data: ResponseData) -> Self:
        """Create a GetMarketsRegionIdOrders instance from ESI response data."""
        logger.info("Creating GetMarketsRegionIdOrders instance from response data")
        operation_id = "GetMarketsRegionIdOrders"
        if response_data.request.operation_id != operation_id:
            raise ValueError(
                f"Expected operation_id {operation_id}, got {response_data.request.operation_id}"
            )
        region_id = int(response_data.request.path_parameters["region_id"])
        orders_by_type: dict[int, CollectedMarketOrders] = {}
        for item in response_data.data:
            order_item = GetMarketsRegionIdOrdersItem(**item)
            type_id = order_item.type_id
            if type_id not in orders_by_type:
                orders_by_type[type_id] = CollectedMarketOrders(
                    region_id=region_id,
                    type_id=type_id,
                    buy_orders=[],
                    sell_orders=[],
                )
            if order_item.is_buy_order:
                orders_by_type[type_id].buy_orders.append(order_item)
            else:
                orders_by_type[type_id].sell_orders.append(order_item)
        # sort the keys in orders_by_type
        orders_by_type = dict(sorted(orders_by_type.items()))
        logger.info(
            f"Successfully created GetMarketsRegionIdOrders instance for region {region_id}, processed {len(response_data.data)} orders into {len(orders_by_type)} types."
        )
        return cls.model_validate(
            {
                "operation_id": operation_id,
                "response_date": response_data.response_date,
                "received_at": response_data.received_at,
                "region_id": region_id,
                "orders": orders_by_type,
            }
        )


# ------------------------------------------------------------------------------
# Derived Models
# ------------------------------------------------------------------------------
@dataclass(slots=True)
class OrderSummaryItem:
    """Represents a summary of market orders."""

    type_id: int
    """The type ID of the item."""
    is_buy_summary: bool
    """Whether the summary is for buy orders."""
    five_price: float
    """The price at which five percent of the available items can be transacted."""
    five_orders: int
    """The number of orders available at the five percent price."""
    five_items: int
    """The number of items available at the five percent price."""
    lowest: float
    """The lowest price."""
    highest: float
    """The highest price."""
    total_items: int
    """The total number of items available."""
    total_orders: int
    """The total number of orders."""
    avg_price: float
    """The average price of the available items."""
    filtered_items: int
    """The number of items that did not meet the threshold."""
    filtered_orders: int
    """The number of orders that did not meet the threshold."""


@dataclass(slots=True)
class OrderSummary:
    """Represents a summary of market orders for a specific region and type."""

    region_id: int
    solar_system_id: int | None
    type_id: int
    buy_summary: OrderSummaryItem
    sell_summary: OrderSummaryItem


class OrderSummaries(BaseModel):
    received_at: int
    region_id: int
    solar_system_id: int | None
    filter_factor: float
    summaries: dict[int, OrderSummary]
